[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ex09Yabdelgh"
version = "0.0.1"
authors = [
  { name="yabdelgh", email="yabdelgh@1337.student.ma" },
]
description = "A small example package"
readme = "README.md"
requires-python = "==3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]